[font]
size   = 8.0

[font.normal]
family = "Hermit"
style = "Regular"

[font.bold]
family = "Hermit"
style  = "Bold"

[font.bold_italic]
family = "Hermit"
style  = "Bold Italic"

[font.italic]
family = "Hermit"
style  = "Italic"


[font.offset]
x = 1
y = 1
