#!/bin/bash

hdd() {
    free="$(df -h /home | awk '/dev/ {print $3}' | sed 's/G/Gb/')"
    perc="$(df -h /home | awk '/dev/ {print $5}')"
    number="$(df -h /home | awk '/dev/ {print $5}' | sed 's/%//')"
    
    echo " $perc($free)"
    }

	echo $(hdd)
