#! /bin/bash

hc(){
	herbstclient "$@"
}


hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#1d2021'
hc set frame_bg_active_color '#ebdbb2'
hc set frame_border_width 1
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 0

hc attr theme.active.color '#98971a'
hc attr theme.active.border_width 3
hc attr theme.active.inner_width 1

hc attr theme.normal.color '#928374'
hc attr theme.normal.border_width 3
hc attr theme.normal.inner_width 1

hc attr theme.urgent.color '#d65d0e'
hc attr theme.inner_color '#ebdbb2'

hc attr theme.floating.border_width 5
hc attr theme.floating.outer_width 4
hc attr theme.floating.outer_color '#b16286'

hc set frame_gap 4
hc set window_gap 10
hc set frame_padding 0
hc set smart_window_surroundings on
hc set smart_frame_surroundings off
hc set mouse_recenter_gap 0
