#! /bin/sh



#
# ┳┓┏┓┏┓┓ ┏┳┳┓┳┓┏┓
# ┣┫┗┓┃┃┃┃┃┃┃┃┣┫┃ 
# ┻┛┗┛┣┛┗┻┛┛ ┗┛┗┗┛
#                



#--------------autostart---------#
#--------------------------------#
set-bg &
$HOME/.config/polybar/launch.sh
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x dunst > /dev/null || dunst &
pgrep -x nm-applet > /dev/null || nm-applet &


#-----fix cursor-----#
#--------------------#
xsetroot -cursor_name left_ptr

#-----removing pre-existing rules--------#
#----------------------------------------#
bspc rule -r '*'


#--------------------tags----------------#
#----------------------------------------#
bspc monitor -d 1 2 3 4 5 6 7 8 9 10



#-------------gaps---------#
#--------------------------#
bspc config window_gap          12


#---------Bordes-------#
#----------------------#
bspc config border_width         3
bspc config normal_border_color  "#D5C4A1"
bspc config focused_border_color "#CC241D"
bspc config urgent_border_color  "#D65D0E"
bspc config presel_border_color  "#EBDBB2"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true




#--------multihead behavior-----#
#-------------------------------#
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

#---------focusing behavior----#
#------------------------------#
bspc config focus_follows_pointer false
bspc config history_aware_focus true
bspc config focus_by_distance true


#--------------rules--------------#
#---------------------------------#
bspc config external_rules_command "$HOME"/.config/bspwm/scripts/externalRules


#-------------scratchpad rules----------#
#---------------------------------------#
bspc rule -a Scpad sticky=on state=floating rectangle=1200x450+0+0 center=on
bspc rule -a Music sticky=on state=floating rectangle=1200x450+0+0 center=on
bspc rule -a Spfm sticky=on state=floating rectangle=1200x450+0+0 center=on
