#! /bin/sh


#
# ┏┓┏┓┏┓┏┳┓┏┓┳┓┳┓┏┓┓   ┳┓┳┳┓ ┏┓┏┓
# ┣  ┃┃  ┃ ┣ ┣┫┃┃┣┫┃   ┣┫┃┃┃ ┣ ┗┓
# ┗┛┗┛┗┛ ┻ ┗┛┛┗┛┗┛┗┗┛  ┛┗┗┛┗┛┗┛┗┛
#                               




wid=$1
class=$2
instance=$3
consequences=$4

result() {
    eval "$consequences"
    [ "$state" ] || echo "$1"
}

case "$class" in
    mpv)
        result "state=floating focus=on rectangle=1200x450+0+0 center=on"
        ;;
    whatsdesk|TelegramDesktop)
        result "desktop=^9 follow=on"
        ;;
    Pavucontrol)
        result "state=floating focus=on rectangle=1200x450+0+0 center=on"
        ;;
    Thunar)
        result "state=floating focus=on rectangle=1200x450+0+0 center=on"
        ;;
    firefox|Navigator)
        result "desktop=^3 follow=on"
        ;;
    Spotify)
        result "desktop=^2 follow=on"
        ;;
esac


case "$instance" in
    Toolkit)
        result "state=floating sticky=on rectangle=500x290+1054+593"
        ;;
esac
