#!/bin/sh

set-bg &                       # set the background with the `setbg` script


autostart="picom dunst unclutter"

for program in $autostart; do
        pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
#[ -n "$xrdbpid" ] && wait "$xrdbpid"

